### ISSUE TITLE
Cool! How to compile?

### ISSUE THREAD

**Issue by orefalo** [iCyberon/pg_ulid#2]
On OSX, I get

/usr/local/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.shlib:309: warning: ignoring old commands for target `pg_ulid.so'
make: Circular pg_ulid.so <- pg_ulid.so dependency dropped.
go build -buildmode=c-shared -o pg_ulid.so main.go pg_ulid.go
pg_ulid.go:12:2: cannot find package "github.com/oklog/ulid" in any of:
	/usr/local/Cellar/go/1.12.3/libexec/src/github.com/oklog/ulid (from $GOROOT)
	/Users/orefalo/go/src/github.com/oklog/ulid (from $GOPATH)
make: *** [pg_ulid.so] Error 1

Any idea?

**Comment by iCyberon** [comment]
Run `go get github.com/oklog/ulid` before `make`. Let me know if it doesn't work
